autoInstallPeers: false
packages:
  - "packages/provider"
  - "packages/railgun"
  - "packages/privacy-pools"
  - "packages/plugins"
  - "examples/pq-account"
  - "docs"
  - "packages/tc-js"
  - "packages/railgun-js"
