apiVersion: v1
kind: Secret
metadata:
  name: pca-595-secrets
  labels:
    {{- include "pca-595.labels" . | nindent 4 }}
type: Opaque
stringData:
  alignment-api-key: "{{ .Values.pca.alignment.apiKey }}"
  iit-api-key: "{{ .Values.pca.iit.apiKey }}"
  iris-api-key: "{{ .Values.pca.driver.apiKey }}"
