//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterDelta) DeepCopyInto(out *ParameterDelta) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterDelta.
func (in *ParameterDelta) DeepCopy() *ParameterDelta {
	if in == nil {
		return nil
	}
	out := new(ParameterDelta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ParameterDelta) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterDeltaList) DeepCopyInto(out *ParameterDeltaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ParameterDelta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterDeltaList.
func (in *ParameterDeltaList) DeepCopy() *ParameterDeltaList {
	if in == nil {
		return nil
	}
	out := new(ParameterDeltaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ParameterDeltaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterDeltaSpec) DeepCopyInto(out *ParameterDeltaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterDeltaSpec.
func (in *ParameterDeltaSpec) DeepCopy() *ParameterDeltaSpec {
	if in == nil {
		return nil
	}
	out := new(ParameterDeltaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterDeltaStatus) DeepCopyInto(out *ParameterDeltaStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterDeltaStatus.
func (in *ParameterDeltaStatus) DeepCopy() *ParameterDeltaStatus {
	if in == nil {
		return nil
	}
	out := new(ParameterDeltaStatus)
	in.DeepCopyInto(out)
	return out
}
