name: Check Secrets
on:
  workflow_call:
    outputs:
      available:
        value: ${{ jobs.check.outputs.available }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      available: ${{ steps.check.outputs.available }}
    steps:
      - id: check
        env:
          SECRET: ${{ secrets.RPC_URL_MAINNET }}
        run: |
          if [ -n "$SECRET" ]; then
            echo "available=true" >> "$GITHUB_OUTPUT"
          fi
