name: CI TC Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-tc-rust:
    runs-on: ubuntu-latest
    env:
      RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
      RPC_URL_SEPOLIA: ${{ secrets.RPC_URL_SEPOLIA }}
      DEV_KEY: ${{ secrets.DEV_KEY }}
      DEV_ADDRESS: ${{ secrets.DEV_ADDRESS }}
      DEV_VIEWING_KEY: ${{ secrets.DEV_VIEWING_KEY }}
      DEV_SPENDING_KEY: ${{ secrets.DEV_SPENDING_KEY }}
    steps:
    - uses: actions/checkout@v5

    # - uses: ./.github/actions/load-sops-secrets
    #   with:
    #     age_key: ${{ secrets.SOPS_AGE_KEY }}

    - uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-primary-key: never

    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: nix develop .#ci --command cargo test

    - name: Run sync
      run: nix develop .#ci --command bash -c "cd crates/tc-rs && just integration-sync"

    - name: Run sync-relayer
      run: nix develop .#ci --command bash -c "cd crates/tc-rs && just integration-sync-relayer"
