name: CI TC JS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-tc-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    # - uses: ./.github/actions/load-sops-secrets
    #   with:
    #     age_key: ${{ secrets.SOPS_AGE_KEY }}

    - uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-primary-key: never

    - uses: Swatinem/rust-cache@v2

    - run: nix develop .#ci-js --command bash -c "cd packages/tc-js && pnpm install"

    - name: Pack wasm
      run: nix develop .#ci-js --command bash -c "cd packages/tc-js && just wasm"
      with:
        RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
        RPC_URL_SEPOLIA: ${{ secrets.RPC_URL_SEPOLIA }}
        DEV_KEY: ${{ secrets.DEV_KEY }}
        DEV_ADDRESS: ${{ secrets.DEV_ADDRESS }}
        DEV_VIEWING_KEY: ${{ secrets.DEV_VIEWING_KEY }}
        DEV_SPENDING_KEY: ${{ secrets.DEV_SPENDING_KEY }}

    - name: Run transact
      run: nix develop .#ci-js --command bash -c "cd packages/tc-js && just integration-transact"
      with:
        RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
        RPC_URL_SEPOLIA: ${{ secrets.RPC_URL_SEPOLIA }}
        DEV_KEY: ${{ secrets.DEV_KEY }}
        DEV_ADDRESS: ${{ secrets.DEV_ADDRESS }}
        DEV_VIEWING_KEY: ${{ secrets.DEV_VIEWING_KEY }}
        DEV_SPENDING_KEY: ${{ secrets.DEV_SPENDING_KEY }}
