name: Docs

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Lint
        run: pnpm lint
      - name: Build Docs
        run: pnpm --filter docs build
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/dist
